ELVIS-1250-teacher-can-manage-activity-applications
ELVIS-SOFTWARE/elvis pull request #112
Opened 2024-09-27 15:24 UTC by Dim145

Ajouter un paramétrage, une case à cocher "le professeur peut gérer ses demandes d'inscription"

2024-10-03 16:15 UTC, xmaquignon requested changes

2024-10-03 16:15 UTC, xmaquignon commented on app/models/ability.rb
> +    end if user.is_teacher && Parameter.get_value("activity_applications.authorize_teachers", default: false)
ce bloc est trop compliqué : essaie de le rendre plus lisible

2024-10-04 07:10 UTC, Dim145 commented on app/controllers/activities_applications_controller.rb
> +      raise CanCan::AccessDenied unless can? :edit, entry
Pour cet endroit, cela utilise la class ability justement (appel à "can?").
Je le fais comme ça pour deux raisons :
- ability ne compare qu'une class d'objet spécifique. Une liste d'activity application étant une autre class, il faudrait définir d'autres ability. Mais quelle class choisir ? array ? query ? etc.
- La seconde raison, et non des moindres, est l'optimisation. Une grosse quantité de données peut être remonté ici (quelques milliers facilement) sans compter que la query est complexe avec pas mal d'objet inclus. Plutôt que devoir tous rapatrier et de donnée ça à authorize, j'ai préféré faire des batchs de 200 entités qu'on compare une par une afin de s'arrêter dès qu'une ne match pas.

2024-10-04 07:11 UTC, Dim145 commented on app/controllers/activities_applications_controller.rb
> +      raise CanCan::AccessDenied unless can? :manage, application
Pareil ici

2024-10-04 07:11 UTC, Dim145 commented on app/controllers/activities_applications_controller.rb
> +        raise CanCan::AccessDenied unless can? :destroy, activity_application
iden aussi

2024-10-04 07:55 UTC, Dim145 commented on app/controllers/activities_applications_controller.rb
> +    raise CanCan::AccessDenied unless authorize_teachers && (current_user&.is_admin || current_user&.is_teacher)
Je dirais que non, ici, je ne veux pas utiliser / définir le droit d'accès à un model ou une partie d'un model. Mais carrément à la page.
Cela ne correspond donc pas à l'utilisation de ability qui définit des droits sur un model.
Par contre, cela reste du ressort de cancan d'où le raise.

2024-10-04 07:59 UTC, Dim145 commented on app/controllers/activities_applications_controller.rb
> +    raise CanCan::AccessDenied unless current_user&.is_admin
Pour ici, je dirais que l'on est dans le même cas que pour la méthode "index". Je ne souhaite pas bloquer un model mais une page. Donc ability n'est pas bon.
Cela pourrait être discuté en considérant qu'on bloque l'objet CSV par contre. Mais il ne me semble pas pertinent (car trop restrictif, ou pas suffisamment) puisque qu'on ne peut pas bloquer le CSV d'un model spécifique de cette manière.

2024-10-04 15:02 UTC, xmaquignon approved these changes

2024-10-07 12:33 UTC, merged