ELVIS-915--POC-facture-acquittee
ELVIS-SOFTWARE/elvis pull request #13
Opened 2024-02-12 14:32 UTC by LHP9-Marie-Sophie-GIBON

migration, merge avec master

2024-02-13 13:57 UTC, Dim145 requested changes
Vu qu'une modifications d'une table venant d'un plugin est nécéssaire, il faut que ce code soit déplacer dans le plugin correspondant.

2024-02-13 13:57 UTC, Dim145 commented on db/migrate/20240110112218_add_edited_to_stripe_invoices.rb
> +class AddEditedToStripeInvoices < ActiveRecord::Migration[6.1]
la table est créer par un plugin, du coup cette migration ne passeras pas si le plugin nécéssaire n'est pas actif. A déplacer dans le plugin

2024-02-13 14:19 UTC, LHP9-Marie-Sophie-GIBON commented
je m'en occupe :)

2024-03-12 17:02 UTC, Dim145 requested changes
Tu n'as pas supprimer les migrations comme demander lors de la précédente review...

2024-03-18 15:20 UTC, Dim145 requested changes

2024-03-18 15:20 UTC, Dim145 commented on frontend/components/userPayments/PaymentsManagement.js
> +                `/api/student_payments/invoice/${payer_id}/issued_paid_invoice`,
si ce composant fait appel à une route d'un plugin, c'est que ce dernier doit se trouver dans ce plugin. Et surchargé le composant si besoin est. 
Aucunes références à un plugin dans le coeur

2024-04-04 13:32 UTC, Dim145 approved these changes

2024-04-04 13:32 UTC, merged