ELVIS--1034-activité-select
ELVIS-SOFTWARE/elvis pull request #16
Opened 2024-03-04 13:28 UTC by LHP9-Marie-Sophie-GIBON

tri du select "famille" par ordre alphabétique

2024-03-05 13:11 UTC, xmaquignon requested changes

2024-03-05 13:11 UTC, xmaquignon commented on app/controllers/activity_ref_kind_controller.rb
> +    @activity_ref_kinds = ActivityRefKind.order(:label)
je pense que tu n'as pas testé ce code

2024-03-05 13:59 UTC, LHP9-Marie-Sophie-GIBON commented
pourtant après test, ça fonctionne ... La syntaxe est incorrect ?

2024-03-12 16:58 UTC, Dim145 requested changes

2024-03-12 16:58 UTC, Dim145 commented on app/controllers/activity_ref_kind_controller.rb
>            render json: @activity_ref_kinds.as_json(
Si tu supprime la définition de la variable "@activity_ref_kinds", il faut aussi supprimer son utilisation. A moins qu'elle soit définit ailleurs, mais dans ce cas je veut bien que tu mette un commentaire pour dire où.

2024-03-13 09:28 UTC, LHP9-Marie-Sophie-GIBON commented
Oups c'est une erreur de ma part :)

2024-03-13 12:39 UTC, xmaquignon requested changes

2024-03-13 12:39 UTC, xmaquignon commented on frontend/components/activityRef/ActivityRefBasics.js
> +            activityRefKinds: this.props.activityRefKinds.map(ark => { return { value: ark[1], label: ark[0] } }).sort( (a, b) => a.label.localeCompare(b.label)),
je ne suis pas sûr que ça fonctionne

2024-03-13 13:42 UTC, xmaquignon approved these changes

2024-03-18 15:15 UTC, Dim145 approved these changes

2024-03-18 15:16 UTC, merged