Rattachement compte
ELVIS-SOFTWARE/elvis pull request #23
Opened 2024-03-12 15:06 UTC by Dim145

- Un utilisateur, dit "rattaché" peut être rattaché à un compte utilisateur, dit "principal" (compte utilisateur principal = compte de rattachement)
- Un utilisateur "rattaché" ne peut être rattaché qu'à un seul compte "principal"
- Un utilisateur "rattaché" n'a pas de compte (il ne peut pas se connecter)
- L'utilisateur "rattaché" peut avoir une adresse email ou ne pas en avoir en propre : dans ce cas, il "bénéficie" de l'adresse du compte "principal" au sens où, si on doit lui envoyer un email, ce sera avec l'adresse du compte "principal"

Dans cette proposition, un compte "principal" peut "gérer" tous les utilisateurs "rattachés" :
- Gérer leurs inscriptions (créer, annuler, modifier) :
- Modifier leur profil
- Cette notion est indépendante de la notion de payeur et de celle de responsable légal
- Cette notion est indépendante de la saison : un compte peut être rattaché ou détaché à volonté (part un admin)
- Dans le cas où on détache un utilisateur, il sera nécessaire de lui affecter une adresse email

Désormais, on refuse les doublons d'adresse e-mail

On ne prend plus en compte la notion de payeur pour définir qui gére les inscriptions.

ATTENTION : cette feature est inclus un "breaking change". Comme dit plus haut, les adresses emails doivent être unique. Une intervention sur la base de données (script ou manuel) doit être exécuté afin de rendre les emails uniques aux seins des comptes (utilisateurs non rattachés).

2024-03-17 08:58 UTC, xmaquignon requested changes

2024-03-17 08:58 UTC, xmaquignon commented on app/models/user.rb
> +  NOT_USE_EMAIL_ATTACHED_TO = %w[save validate create update].freeze
remonter en haut de fichier

2024-03-17 08:58 UTC, xmaquignon commented on app/models/user.rb
> +    return tmp if caller.any? { |c| NOT_USE_EMAIL_ATTACHED_TO.any? { |m| c.include?(m) } }
je ne suis pas fan de cette façon de faire
- impact significatif (parcours de la pile d'appel) sur tous les appels à `email` ; dans le cas où on récupère beaucoup de users avec leur email, ça va pénaliser les perf
- on n'aura pas le comportement souhaité si, par exemple, la méthode email est appelée dans le contexte d'une méthode `save` qui n'est pas celle d'ActiveRecord

2024-03-17 08:58 UTC, xmaquignon commented on app/models/user.rb
> +  def email_is_null_if_attached
renommer en 
`clear_dupl_email_if_attached`

2024-03-17 08:58 UTC, xmaquignon commented on frontend/components/AttachAccount.js
> +            <h3>Utilisateurs sélectionnées</h3>
sélectionnées -> sélectionnés

2024-03-17 08:58 UTC, xmaquignon commented on frontend/components/AttachAccount.js
> +                        email (peut-être vide) :
peut-être -> peut être

2024-03-17 08:58 UTC, xmaquignon commented on frontend/components/AttachAccount.js
> +                            text: "Voulez-vous vraiment attacher ces utilisateurs au compte de rattachement ? Cela va supprimer le mot de passe des comptes rattaché. Ces derniers ne pourront donc plu
1. des comptes rattachéS
2. Ces derniers... plus se connectER

2024-03-17 08:58 UTC, xmaquignon commented on frontend/components/AttachAccount.js
> +                                            text: "Les comptes ont bien été attachés"
ont bien été attaché

2024-03-17 08:58 UTC, xmaquignon commented on frontend/components/AttachAccount.js
> +                >
extraire vers un composant `UserListItem`

2024-03-17 08:58 UTC, xmaquignon commented on frontend/components/AttachAccount.js
> +                    onClick={() => {
refactoriser le handler de `onClick` pour le rendre plus lisible et maintable

2024-03-17 08:58 UTC, xmaquignon commented on frontend/components/detachAccount.js
> +                Ce dernier deviendras indépendant, c'est à dire qu'il pourras se connecter et géré son compte.
Ce dernier deviendra indépendant, c'est à dire qu'il pourra se connecter et gérer son compte.

2024-03-17 08:58 UTC, xmaquignon commented on frontend/components/detachAccount.js
> +                Il vous est cependant toujours possible de géré son compte si vous créez un lient familial avec lui.
Il vous est cependant toujours possible de gérer son compte si vous créez un lien familial avec lui.

2024-03-17 08:58 UTC, xmaquignon commented on frontend/components/detachAccount.js
> +                P.S: ce nouvel email ne doit pas être déjà utilisé par un autre utilisateur.
Pour détacher un compte, vous devez lui ajouter une adresse email (si il n'en a pas déjà une). C'est à cette adresse que sera envoyé le lien lui permettant de se connecter. <br/>

NB : ce nouvel email ne doit pas être déjà affecté à un autre utilisateur.

2024-03-17 08:58 UTC, xmaquignon commented on frontend/components/detachAccount.js
> +
Conservé -> Conserver

2024-03-17 08:58 UTC, xmaquignon commented on frontend/components/userForm/ContactForm.js
> +                        console.log("form.getState().values", form.getState().values)
à commenter

2024-03-18 10:55 UTC, Dim145 commented on app/controllers/users_controller.rb
> +  def detach
plutôt detach_user car on ne peut en détacher qu'un seul à la fois

2024-03-18 12:47 UTC, xmaquignon approved these changes

2024-03-18 12:49 UTC, merged