Possibilité de sélectionner les payeurs dans le userform
ELVIS-SOFTWARE/elvis pull request #26
Opened 2024-03-14 11:38 UTC by Dim145

Dans l'étape 2, dans le parcours d'inscription. Ajouter un select multiples (comme choix des professeurs d'une activité) pour indiquer le payeur. Dans cette liste apparaissent tous les comptes utilisateurs liées par un lien familial et le compte de l'utilisateur en train de réaliser l'inscription.

![image](https://github.com/ELVIS-SOFTWARE/elvis/assets/50747004/5e7d0173-058a-4537-81ff-19dd908f8ef6)

2024-03-17 09:30 UTC, xmaquignon requested changes

2024-03-17 09:30 UTC, xmaquignon commented on app/controllers/activities_applications_controller.rb
je pense qu'il faudrait déporter ces "fix" ailleurs

2024-03-17 09:30 UTC, xmaquignon commented on app/controllers/payments_controller.rb
>        }
Si,pour obtenir les payeurs, on ne peut pas utiliser 
```ruby
user.get_users_paying_for_self(s)
```

alors il faut intégrer ce code dans la classe `User` pour respecter le principe SRP et rendre possible sa réutilisabilité

2024-03-17 09:30 UTC, xmaquignon commented on app/controllers/users_controller.rb
> +
ce code ressemble beaucoup à celui que l'on trouve dans `activities_application_controller.rb`

ça doit être possible de factoriser

2024-03-17 09:30 UTC, xmaquignon commented on app/helpers/payment_helper.rb
> +
ce code ressemble beaucoup à celui de `payments_controller` (méthode `generate_data_for_payment_summary_table`)

2024-03-18 07:58 UTC, Dim145 commented on app/controllers/payments_controller.rb
>        }
Comme vue ensemble, préféré une méthode private dans le controlleur car ce code est très spécifique (formater) pour l'aafichage de cette page

2024-03-18 09:02 UTC, Dim145 commented on app/helpers/payment_helper.rb
> +
C'est vrai. Toute la méthode du helper se ressemble en même temps. La différence réside dans le type des données (model ou json) et le fait que l'une prennent en compte les options et l'autre nan. Il faudrait unifié les 2. Je créer un tocket pour cela qui devras être traité plus tard (pas de rapport avec cette PR)

2024-03-18 17:36 UTC, xmaquignon approved these changes

2024-03-18 17:36 UTC, merged