ELVIS--1109-Créneau-edit-modal
ELVIS-SOFTWARE/elvis pull request #38
Opened 2024-04-12 09:15 UTC by LHP9-Marie-Sophie-GIBON

modifier un créneau de cours via la modal d'édition

2024-05-17 09:19 UTC, Dim145 requested changes

2024-05-17 09:19 UTC, Dim145 commented on frontend/components/planning/Planning.js
> +                    if (data.error_message) {
Si on rentre dans ce if, il ne faut surement pas que le reste de la fonction s'éxécute nan ? Il faudrait donc un return (ou un else)

2024-05-21 12:35 UTC, LHP9-Marie-Sophie-GIBON commented on app/services/activities/time_interval_updater.rb
> +      instances_to_check = instances_to_update
c'est pour être plus clair, d'autant que j'ai repris le code originel ... l'utilisation dese deux variables permet de séparer les instances d'activités qui doivent etre mises à jour( instances_to_update) de celles qui doivent etre vérifiées (instances_to_update), tout en permettant l'ajout de nouvelles instances à vérifier (par ex, si une instance d'activité correspondante n'est pas trouvée pour un nouvel intervalle de temps généré)

2024-05-22 07:32 UTC, Dim145 approved these changes

2024-05-22 07:39 UTC, merged