ZIGGY-885--Wizard-Coordonnées
ELVIS-SOFTWARE/elvis pull request #41
Opened 2024-04-29 14:25 UTC by LHP9-Marie-Sophie-GIBON

mise en forme de l'étape 2

2024-05-16 15:31 UTC, Dim145 requested changes

2024-05-16 15:31 UTC, Dim145 commented on frontend/components/userForm/HandicapInfos.js
> +            <h4 style={{color: "#8AA4B1"}}>INFORMATIONS COMPLEMENTAIRES</h4>
Même remarque pour les majuscules

2024-05-16 15:31 UTC, Dim145 commented on frontend/components/userForm/UserForm.js
> +                    <h4 style={{color: "#8AA4B1"}}>INFORMATIONS PERSONNELLES DE {initialValues.first_name.toUpperCase()}</h4>
majuscules...

2024-05-21 09:09 UTC, LHP9-Marie-Sophie-GIBON commented on frontend/components/common/InputSelect.js
> +            {!inline && !className && <label htmlFor={input.name}>
le label rend un bug visuel (un saut de ligne) et commme l'input select est utilisé dans beaucoup de composant, la solution du classname me permet de conditionner le rendu pour cette page sans affecter les autres

2024-05-22 07:24 UTC, Dim145 approved these changes

2024-05-22 07:24 UTC, merged