ELVIS-1141-Mes-Demandes-d'inscription
ELVIS-SOFTWARE/elvis pull request #46
Opened 2024-05-17 13:30 UTC by LHP9-Marie-Sophie-GIBON

refont design de la page

2024-05-22 07:17 UTC, Dim145 requested changes

2024-05-22 07:17 UTC, Dim145 commented on frontend/components/PreApplication.js
> +            {user.avatar ? (
Il y as maintenant beaucoup d'endroit où l'avatar est afficher. Avec en plus la même règle (si pas d'avatar, on affiche les initiales), cela serait bien d'avoir un composant qui affiche l'avatar du user donnée en props.

2024-05-22 07:17 UTC, Dim145 commented on frontend/components/activityItems/NewActivityItem.js
> +                                <a href={`/inscriptions/${this.state.activityApplicationId}`}>{`0${this.state.activityApplicationId}`}</a> :
Toujours ajouter un 0 devant n'est pas une solution quand on veut toujours 3 chiffres. Et le jours ou il y auras une centaine d'activities ?
Il faut trouver une solution un peu plus séduisante (qui existe déjà avec padStart sur string)

2024-05-22 07:17 UTC, Dim145 commented on frontend/components/activityItems/RenewActivityItem.js
> +                                `0${this.state.preApplicationActivity.activity_application.id}`}
Même chose pour le 0

2024-05-23 08:42 UTC, LHP9-Marie-Sophie-GIBON commented on frontend/components/PreApplication.js
> +        let openingPeriod = openingDate < 10 ? 'début' : openingDate > 20 ? 'fin' : 'mi';
je vais plutot remettre les vrais dates ... j'avoue que j'ai suivi un peu trop à la lettre la maquette ..

2024-05-23 13:46 UTC, Dim145 approved these changes

2024-05-23 13:46 UTC, merged