ZIGGY-886-Wizard-Résumé
ELVIS-SOFTWARE/elvis pull request #47
Opened 2024-05-21 11:38 UTC by LHP9-Marie-Sophie-GIBON

2024-05-22 06:45 UTC, Dim145 requested changes

2024-05-22 06:45 UTC, Dim145 commented on frontend/components/activityApplications/TimePreferencesTable.js
> +    const timeTable = useMemo(() => preferences.length > 0 ? preferences.map(createTimeTable) : null, [preferences]);
cela porte mal son nom. Ce n'est pas la table en sois, c'est juste les lignes de la table... (pareil pour le nom de la fonction appelée)

2024-05-22 06:45 UTC, Dim145 commented on frontend/components/activityApplications/Validation.js
> +        is_accompanying ? accompanying.push({name: `${first_name} ${last_name}`}) : null;
on n'utilise pas une ternaire en dehors d'une affectation de variable (ou dans un appel de methode)? Il vaut mieux utilisée un if afin que cela sois plus simple à lire (et plus joli je trouve aussi)

2024-05-22 09:16 UTC, LHP9-Marie-Sophie-GIBON commented on frontend/components/activityApplications/EvaluationChoiceTable.js
> +    let ref = activityRefs[0];
la première référence d'activité (activityRefs[0]) est utilisée comme valeur par défaut pour la variable ref. Ensuite, dans la boucle map, cette valeur par défaut est remplacée si une correspondance est trouvée dans le tableau activityRefs pour l'id actuel (refId).

2024-05-22 09:28 UTC, LHP9-Marie-Sophie-GIBON commented on frontend/components/activityApplications/SelectedActivitiesTable.js
> +            duration: group[0].duration,
si la durée de l'activité est indiquée (table activityRefs), celle ci s'applique à tous les items se référant à cette activité :)

2024-05-23 09:22 UTC, Dim145 requested changes

2024-05-23 09:22 UTC, Dim145 commented on app/services/users/search_user.rb
> +        user["avatar"] = u.avatar_url
alors du coup vu que tu en as fait une méthode, il n'y as pas besoin de le mettre ici. il faut ajouter la méthode dans les includes (@includes). On ne peut peut-être (et même surement) pas toujours l'url de l'avatar.

2024-05-23 09:22 UTC, Dim145 commented on app/controllers/users_controller.rb
> +  }
ici tu transforme methods en tableau et ajoute ta méthode avatar_url (fait à plein d'autre endroit dans le code)

2024-05-23 13:54 UTC, Dim145 requested changes

2024-05-23 13:54 UTC, Dim145 commented on app/controllers/users_controller.rb
> +  puts 'test'
Attention aux puts de test

2024-05-24 08:39 UTC, Dim145 approved these changes

2024-05-24 08:41 UTC, merged