Update Webpacker and all permited without this old version
ELVIS-SOFTWARE/elvis pull request #51
Opened 2024-05-31 10:03 UTC by Dim145

Updated webpacker to last stable version

Updated node version to 20
Updated ruby version to 3.3.2

Updated rails to 7

Remove version restriction of the majority of gems (like sidekiq)

Majority of packages.json libs not touched because can have breaking changes like react-table.

Warning, upgrade to rails 7 break all plugin with rails 6 restriction. Update your plugins BEFORE update Elvis.

2024-06-04 07:46 UTC, xmaquignon requested changes
Ne pas upgrade Rails pour l'instant

2024-06-04 07:46 UTC, xmaquignon commented on Dockerfile
> +FROM ruby:3.3.1-slim AS build
version cible =  3.3.1 ou 3.3.2 ? (cf `.ruby-version$`)

2024-06-04 07:46 UTC, xmaquignon commented on Dockerfile
> +#ENV LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so.2
suppression de `jemalloc` ??

2024-06-04 07:46 UTC, xmaquignon commented on Dockerfile
> +#ENV LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so.2
supression de `jemalloc` ?

2024-06-04 07:46 UTC, xmaquignon commented on Gemfile
>  # forcer < 1.9 pour éviter le bug https://github.com/ruby-i18n/i18n/issues/603
commentaire à supprimer

2024-06-04 07:46 UTC, xmaquignon commented on config/environments/production.rb
> +  config.active_support.report_deprecations = false
pourquoi masquer les deprecations ? idem pour l'environnement kubernetes

2024-06-04 07:46 UTC, xmaquignon commented on db/schema.rb
> +
à supprimer

2024-06-04 07:46 UTC, xmaquignon commented on db/schema.rb
> +
à supprimer

2024-06-04 07:46 UTC, xmaquignon commented on db/schema.rb
> +
à supprimer

2024-06-04 07:46 UTC, xmaquignon commented on db/schema.rb
> +    t.string "dev_stripe_current_subscription_status"
à supprimer

2024-06-04 07:46 UTC, xmaquignon commented on db/schema.rb
>      t.string "handicap_description"
restaurer le type de `adherent_number` à `serial`

2024-06-04 07:46 UTC, xmaquignon commented on db/schema.rb
> +  add_foreign_key "activity_ref_dolibarr_links", "activity_ref_pricings"
à supprimer

2024-06-04 07:46 UTC, xmaquignon commented on db/schema.rb
>    add_foreign_key "due_payments", "payment_schedules"
à supprimer

2024-06-04 08:10 UTC, Dim145 commented on Dockerfile
> +#ENV LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so.2
Non, ce n'était pas sencé être commit. Je corrige ça

2024-06-14 07:56 UTC, xmaquignon approved these changes

2024-06-14 07:56 UTC, merged